import type { PullsListResponse } from "../git";

export const generatePrBody = (
    emoji: string,
    pickedPRs: PullsListResponse["data"],
    totalSelectedPRs: number,
    successCount: number,
    skipCount: number,
): string => {
    const prList = pickedPRs
        .map((pr) => `- #${pr.number}: ${pr.title} (@${pr.user?.login})`)
        .join("\n");

    return `## ${emoji} Cherri Summary

This PR contains cherry-picked commits from the following PRs:

${prList}

### Details
- **Total PRs selected**: ${totalSelectedPRs}
- **PRs with picked commits**: ${pickedPRs.length}
- **Commits cherry-picked**: ${successCount}
- **Commits skipped**: ${skipCount}

### Generated by Cherri
This PR was automatically created by the [Cherri](https://github.com/bnn16/cherri) tool for cherry-picking PRs marked with ${emoji}.`;
};
